---
- hosts: workstation

  tasks:
    - name: install SizeUp
      mac_pkg: pkg_type=app
               url=http://www.irradiatedsoftware.com/download/SizeUp.zip
               archive_type=zip archive_path=SizeUp.app

